// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5HrAZNQnfVwWyZUvqckqyxHZOgX4lmY',
    appId: '1:936051926953:web:31e6a73731fe78d7a506b8',
    messagingSenderId: '936051926953',
    projectId: 'bloc-gallary-library',
    authDomain: 'bloc-gallary-library.firebaseapp.com',
    storageBucket: 'bloc-gallary-library.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKMFFf_KX5vJNbcRTSUcP6sEAyr6dckYg',
    appId: '1:936051926953:android:b2d494a40f6f9a4fa506b8',
    messagingSenderId: '936051926953',
    projectId: 'bloc-gallary-library',
    storageBucket: 'bloc-gallary-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmpgfolXEx3MffaK0UALPtiX083b6zyxg',
    appId: '1:936051926953:ios:cca191c41d577cc9a506b8',
    messagingSenderId: '936051926953',
    projectId: 'bloc-gallary-library',
    storageBucket: 'bloc-gallary-library.appspot.com',
    iosBundleId: 'com.example.blocPhotoLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmpgfolXEx3MffaK0UALPtiX083b6zyxg',
    appId: '1:936051926953:ios:f0e7fdffa395b555a506b8',
    messagingSenderId: '936051926953',
    projectId: 'bloc-gallary-library',
    storageBucket: 'bloc-gallary-library.appspot.com',
    iosBundleId: 'com.example.blocPhotoLibrary.RunnerTests',
  );
}
